doc : modify troubleshooting scenario to use description lists
crc-org/docs pull request #10
Opened 2024-12-02 10:01 UTC by rohanKanojia

# Description

Follow up PR to https://github.com/crc-org/docs/pull/8 to address review comment from @themr0c

2024-12-02 10:10 UTC, themr0c commented on modules/ROOT/pages/troubleshooting.adoc
> +.. Go to start and open `Event Viewer`
Nitpick

```suggestion
.. Go to start and open `Event Viewer`.
```

2024-12-02 10:10 UTC, themr0c approved these changes

2024-12-02 10:12 UTC, themr0c commented on modules/ROOT/pages/troubleshooting.adoc
> +   Find log file in `~/.crc/vfkit.log`
Another nitpick for consistency with previous sentence:

```suggestion
   Find the log file in `~/.crc/vfkit.log`
```

2024-12-02 10:38 UTC, gbraad requested changes
As mentioned by Fabrice.
Avoid stylizing text to draw attention.

2024-12-04 08:22 UTC, themr0c approved these changes

2024-12-04 09:17 UTC, merged